### ISSUE TITLE
Elan trackpad doesnt work , and i cant boot into windows .

### ISSUE THREAD

**Issue by putraalm** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#12]
Can you fix the multiboot?

**Comment by Ab2774** [comment]
Hi, can you please provide me with a copy of IOReg so that we can diagnose why the Trackpad isn't working?
And for the EFI, you can use my EFI till I publish the new release soon 
[EFI.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/6097333/EFI.zip)

**Comment by Flabib** [comment]
Hi, when you upload another update bro? I hope you update OpenCore version for this device

**Comment by Ab2774** [comment]
> Hi, when you upload another update bro? I hope you update OpenCore version for this device

Hi, I'm sorry but I've been struggling lately with my mental health and with my relationship, I'll release a new update in the next weeks, unfortunately, it might be the last since I'm buying an M1 MacBook Pro for college.
Thanks!

**Comment by mteguhfh** [comment]
The elantech doesn't work. Stuck at magicmouse animation askin for turnit on

**Comment by Ab2774** [comment]
> The elantech doesn't work. Stuck at magicmouse animation askin for turnit on

Please attach a copy of [IORegistryExplorer](https://github.com/vulgo/IORegistryExplorer/releases/tag/v2.1) to diagnose what's causing the problem.
Cheers

**Comment by mteguhfh** [comment]
No, sorry everything is working now ❤️❤️❤️, i format the whole SSD, and delete the efi folder on usb and replace with yours opencore latest and trim ssd because i'm in bigsur, and voila magic happen. 

Thank you very much, and wifi too using your mention itlwm and airportitlwm :) love love love
