### ISSUE TITLE
HELP ME! (Wi-Fi Card)

### ISSUE THREAD

**Issue by sh-topor** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#14]
Hi. Did you modify your BIOS to delete wi-fi card whitelist? My Wi-Fi Card from AliExpress BCM94360NG

**Comment by sh-topor** [comment]
I am going to use Hack and Win at the same time

**Comment by Ab2774** [comment]
Hi, I actually didn't modify my BIOS or anything, the card that I bought was Lenovo DW1560, it works for both macOS and Windows, I believe newer Lenovo laptops don't have a whitelist on Wi-Fi cards, the BCM94360NG doesn't require any additional kexts as it's a native card, make sure it's installed correctly, then install Windows via Bootcamp to get the drivers like this [guide](https://www.tonymacx86.com/threads/guide-how-to-install-bluetooth-driver-in-the-windows-10-bcm943602cs.253903/), if you still have these problems contact your Aliexpress seller to either replace the card or refund you.
Thanks
