### ISSUE TITLE
Missing OpenCore.efi in the release

### ISSUE THREAD

**Issue by Flabib** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#16]
Did you forget to put OpenCore.efi in the release? and why My OpenCore version is still 0.6.6 when I check in the terminal? I have to try to reset NVRAM but I still can't do that.

I'm very thank you for your update.

**Comment by Ab2774** [comment]
Hi, thanks for reporting, I've fixed it, also, you can check via Hackintool to make sure, if it's still the same, try resetting the NVRAM, you can reset it using the `Reset NVRAM` tool in the boot startup in OpenCore.
Cheers
