### ISSUE TITLE
Clover Problem

### ISSUE THREAD

**Issue by sh-topor** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#17]
Hi, I have problem in Clover. I can see only one button (USB Installer). In other instructions at least 5 buttons in Clover. I can get Disc Utility for Mac and Install Mac OS, but I can't enter in it (because I have only one “USB” button in Clover)

**Comment by Ab2774** [comment]
Hi, use OpenCore please as it's now way more advanced than Clover.
Thanks
