### ISSUE TITLE
Idle Package Power Usage

### ISSUE THREAD

**Issue by brkbrlz16** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#18]
I've been thinking about what can we do about this issue. Mine usually idles at 1.80watts and that's a bit high if you compare it to Windows and battery on this laptop is not good at all (especially considering the wear and age) yet I can sometimes get 5 hours of screen on time on Windows.
I guess we need to look at ASPM and USB power. I think even if we don't use USB ports and SD Card slot macOS still gives some current to them, causing a 1w difference between the Core+DRAM usage and package usage. I know brightness, HDD, SSD also contribute to the package usage but I've seen people getting package usage as low as 0.60 watts on some Thinkpads without VoltageShift and just by tinkering with Thunderbolt power management. I disabled CFG Lock (had to fiddle with RU.efi) and that also made no difference. VoltageShift actually lowers temps a little bit if anyone's interested but I probably went a bit overboard with the offset numbers as I had random crashes.

**Comment by Ab2774** [comment]
Hi, thank you for noticing that, I didn't notice any unusual difference as I tend to use macOS more often than Windows on my laptop.
There are some things we can do to improve that, in the newest release (which I'm gonna publish as soon as CpuTscSync gets fully supported for macOS 12) I added a new kernel extension called [ECEnabler](https://github.com/1Revenger1/ECEnabler), which allows reading EC fields over 1 byte long, meaning that you don't need to patch your battery to get it working fully under macOS, in my case, I didn't need to add any additional patched to get it working but some models do need to add, another thing we can look at is CPU Clock Speed, in macOS, my CPU runs at 2.71 GHz with OpenCore and 2.5 GHz with Clover, another thing is the USB Power, adjusting the USB power via an ACPI table is not the ideal way to do it, that's is why I'm gonna add USBPorts kernel extension in the next release, another thing to consider is the health of your disks which do affect power consumption, in my case, I have to SSDs, one runs Windows and the other have macOS installed, they are not from the same manufacturer, macOS do recognize NTFS disks but Windows doesn't.
The problem most Lenovo laptops have is that the SD card chip is not connected via PCIe port, it is connected as a USB port, which can affect power management, if it's connected via PCIe port, we can use [RealtekCardReader](https://github.com/0xFireWolf/RealtekCardReader) and [RealtekCardReaderFriend](https://github.com/0xFireWolf/RealtekCardReader) to get it fully functional as a native one.
Lastly, we need to remember that all Windows laptops are optimized for Windows, they are made to run Windows, as macOS can run on them, they can't perform as if they are running Windows, my laptop doesn't have any Thunderbolt ports as it's from 2017, trying to get Thunderbolt ports to work under macOS can be tricky, and even if they do, they won't behave the same under Windows comparing to macOS.
Hope that helps
