### ISSUE TITLE
EFI.OpenCore.v1.1.7.zip desn't work on Synaptics

### ISSUE THREAD

**Issue by xnamahx** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#20]
Hi thanks for making this config!

Just a minor thing. In Release EFI.OpenCore.v1.1.7.zip both config.plist are equal, both look for Elan kext. 

So I needed to change the Synaptics version with the correct kext to be able to use the trackpad.

Saludos

**Comment by Ab2774** [comment]
Thanks for the feedback! I think in the next release I'm gonna include them both in one EFI as they don't conflict with other users and don't cause a Kernel Panic for other users.
Thanks
