### ISSUE TITLE
USB 3.1 Gen 1 Type C

### ISSUE THREAD

**Issue by ameenjuz** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#21]
Hi @Ab2774 
Do you have working usb 3.0 or 3.1 on type c port?
Just for confirmation i have bought usb 3.0 type c adapter which is not
Working on my type c port

**Comment by Ab2774** [comment]
Hi, currently I don't have any experience with a Hackintosh with a 3.1 USB port.
In the past, I used SSDT/DSDT approach to get my USB ports working, but then I figured that the best way to get all of the USB ports working at full speed and fully identified by the system is to use a USBPorts.kext generated by Hackintool, before you do anything, make sure you're using the right SMBIOS, using wrong SMBIOS' can disable USB ports sometimes.
1 - Disable all the USB ACPI patches and kexts
2 - Download USBInjectAll from Sniki's repo
3 - Enable it in your bootloader then reboot
4 - Plug in all of your USB devices to identify them in Hackintool
5 - Delete all the unused USB ports in Hackintool and leave SS01-SS03, then generate USBPorts.kext 
6 - Remove USBInjectAll and add USBPorts.kext to your EFI folder and restart
Now all of your ports should work perfectly.
Cheers
