### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#4]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ?? Right now it's fn + f12 and fn + key pause. My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by Ab2774** [comment]
Hi, I don't understand what's your problem, if you're a beginner, search the web for a guide for your laptop, meanwhile try these patches: 
https://github.com/jsassu20/OpenCore-HotPatching-Guide
Please don't open an issue to this laptop repository if it's not related at any kind to it.
Regards
