### ISSUE TITLE
How to boot in safe mode?

### ISSUE THREAD

**Issue by sdykae** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#5]
I need to rebuild spotlight :(

**Comment by Ab2774** [comment]
Hi 
you can boot into Safe Mode by adding -x Boot-arg into Clover and OpenCore Bootloaders

**Comment by sdykae** [comment]
> Hi
> you can boot into Safe Mode by adding -x Boot-arg into Clover and OpenCore Bootloaders

How to add -x to opencore ? Can find that :(
