### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by huadgal** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#8]
Hi, when I'm installing system the progress bar is moving to 100% (it's taking sth about 2 hours) and it's stopping.
When i used -v flag i saw: https://ibb.co/K5JbDCF

huadgal

**Comment by Ab2774** [comment]
Hi @huadgal, it looks like the issue is from the EFI folder itself, please note that my latest release of Clover doesn't support Big Sur, please wait for a couple of days till I get everything ready to release 1.1.5.
Thanks
